name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1' 

      - name: Install dependencies
        run: npm install

      

      - name: Build application
        run: npm run build
        
      - name: Deploy to EC2 (Dev)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  # Ensure this secret is set in your repo
          EC2_HOST: ${{ secrets.EC2_HOST }}              # Ensure this secret is set in your repo
          EC2_USER: ${{ secrets.EC2_USER }}              # Ensure this secret is set in your repo
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./* $EC2_USER@$EC2_HOST:/path/to/your/dev-backend
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "cd /path/to/your/dev-backend && npm install && npm run start"
